#!/system/bin/sh

# does not work on Android Q

LOGFILE=$1
. /etc/init.d/googlewiz.sh

VER=$(getprop ro.build.version.sdk)

echo "-- ro.build.version.sdk = $VER" | $TEE $LOGFILE

if [ $VER -eq 29 ]; then
    echo "-- we're on android 10, not running this script (does not seem to work always)" | $TEE $LOGFILE
    exit 0
fi

waitforsdcard $LOGFILE

dosetprop() {
    echo "-- property: $1 = $2" | $TEE $LOGFILE
    $SETPROP "$1" "$2"
}

doresetprop() {
    VAL1=$($GETPROP $1)
    $RESETPROP "$1" "$2"
    VAL2=$($GETPROP $1)
    echo "-- resetting property: $1 ($VAL1 => $VAL2)" | $TEE $LOGFILE    
}

dosetprop java.net.preferIPv6Addresses false
dosetprop persist.sys.assert.panic 0
dosetprop persist.sys.zram_enabled 0
dosetprop persist.vendor.debug.wfdcdbg 0
dosetprop persist.vendor.debug.wfdcdbgv 0
dosetprop vendor.debug.egl.swapinterval 0

doresetprop persist.rcs.supported 0
doresetprop persist.sys.zram_enabled 0
doresetprop ro.boot.enable_dm_verity 0
doresetprop ro.fota.oem 0
doresetprop ro.vendor.qti.config.zram false
doresetprop vendor.ims.DATA_DAEMON_STATUS 0
doresetprop vendor.ims.ENABLE_HELPER 0
doresetprop vendor.ims.QMI_DAEMON_STATUS 0
doresetprop persist.vendor.qcomsysd.enabled 0

resetprop ctl.stop oemlogkit
resetprop ctl.stop oneplus_brain_service

# below properties are in system.prop but somehow get overwritten
doresetprop net.dns2 1.0.0.1
doresetprop net.hostname uranus
doresetprop net.qtaguid_enabled 0
doresetprop persist.audio.vr.enable false
doresetprop persist.sys.zram_enabled 0
doresetprop persist.vendor.radio.atfwd.start false
doresetprop sys.oem_unlock_allowed 0
doresetprop vendor.ims.DATA_DAEMON_STATUS 0
doresetprop vendor.ims.ENABLE_HELPER 0
doresetprop vendor.ims.QMI_DAEMON_STATUS 0
