#!/system/bin/sh

LOGFILE=$1

. /etc/init.d/googlewiz.sh

sleep 10

GOV=cpufreq
echo "-- setting GPU governor to $GOV" | tee -a $LOGFILE
sysset "$GOV" /sys/kernel/gpu/gpu_governor

if [ -e /sys/kernel/gpu/gpu_min_clock ]; then
    MIN=`cat /sys/kernel/gpu/gpu_freq_table | sed 's/ /\n/g' | sed '/^ *$/d' | sort | head -n 1 | tail -n 1`
    echo "-- boosting gpu minimal frequency to $MIN" | tee -a $LOGFILE
    echo $MIN > /sys/kernel/gpu/gpu_min_clock
else
    echo "-- /sys/kernel/gpu/gpu_min_clock does not exist" | tee -a $LOGFILE
fi

echo "-- disable GPU throttling" | tee -a $LOGFILE
sysset 0 /sys/class/kgsl/kgsl-3d0/throttling
echo "-- disable GPU napping" | tee -a $LOGFILE
sysset 0 /sys/class/kgsl/kgsl-3d0/force_no_nap
