#!/system/bin/sh

# does not work on Android Q

LOGFILE=$1
. /etc/init.d/googlewiz.sh

# for some reason script /vendor/etc/vendor.memplus.sh keeps hanging
# in an endless sleep loop
# terminate it by setting vendor.sys.memplus.postboot to 2

if /system/bin/grep '/vendor/etc/vendor.memplus.sh' `$TB ps -A -o user,pid,ppid,nice,args`; then
    echo "-- process 'sh /vendor/etc/vendor.memplus.sh' is running" | $TEE $LOGFILE
else
    echo "-- process 'sh /vendor/etc/vendor.memplus.sh' is NOT running" | $TEE $LOGFILE
fi

SLEEP=10
echo "-- sleeping $SLEEP seconds before setting vendor.sys.memplus.postboot to 2" | $TEE $LOGFILE

sleep $SLEEP
$SETPROP vendor.sys.memplus.postboot 2
