#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

sleep 15

if [ -e /dev/block/zram0 ]; then
    echo "-- turning off swap for /dev/block/zram0" | $TEE $LOGFILE
    $TB swapoff /dev/block/zram0
fi
if [ -e /dev/block/vnswap0 ]; then
    echo "-- turning off swap for /dev/block/vnswap0" | $TEE $LOGFILE
    $TB swapoff /dev/block/vnswap0
fi
