#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

waitforsdcard $LOGFILE

dosetprop() {
    echo "-- property: $1 = $2" | $TEE $LOGFILE
    $SETPROP "$1" "$2"
}

# The global logging level
# VERBOSE, DEBUG, INFO, WARN, ERROR, ASSERT or SILENT
# Only the first character is the key character.
# set logging level to Silent
dosetprop log.tag S
