#!/system/bin/sh

LOGFILE=$1

. /etc/init.d/googlewiz.sh

waitforsdcard $LOGFILE

CMD=/system/bin/cmd
CNT=0
GETPROP='toolbox getprop'

sleep 10

OUTLOOK=/sbin/.core/modules/substratum/system/app/_com.microsoft.office.outlook.SwiftBlack.OxygenOS.apk

OCNT=0
if [ ! $($GETPROP ro.build.version.sdk) -eq 29 ]; then
    # enable all overlays which are not yet enabled
    for o in `$CMD overlay list | grep '\[ \]' | awk '{print $3}' | grep -v cmcc | grep -v cutout`; do
        echo "-- enable overlay $o" | tee -a $LOGFILE
        $CMD overlay enable $o
        OCNT=$(( $OCNT + 1 ))
    done
else
    # enable all overlays which are not yet enabled BUT only those with Switft inside !
    echo "-- enabling Swift overlays on Android Q" | tee -a $LOGFILE
    for o in $($CMD overlay list | grep '\[ \]' | awk '{print $3}' | grep -v cmcc | grep -v cutout | grep Swift); do
        echo "-- enable Swift overlay $o" | tee -a $LOGFILE
        $CMD overlay enable $o
        OCNT=$(( $OCNT + 1 ))
    done
    
    echo "-- enabling non-Swift overlays on Android Q" | tee -a $LOGFILE

    for i in overlay.tiles.QSTiles5Col4Rows overlay.fingerprint.white com.android.systemui.tiles.PixelBlack com.android.systemui.statusbars.PixelBlack; do
        echo "   enable non-Swift overlay $i" | tee -a $LOGFILE
        $CMD overlay enable $i
        OCNT=$(( $OCNT + 1 ))
    done
fi
echo "-- $OCNT overlays were enabled" | tee -a $LOGFILE
