#!/system/bin/sh

LOGFILE=$1

echo "-- not running script $0 ... seems not needed" | tee -a $LOGFILE
exit 0


waitforsdcard $LOGFILE

sleep 10

echo "-- running update_verifier to signal successful boot" | tee -a $LOGFILE
/system/bin/update_verifier
