#!/system/bin/sh

# does not work on Android Q

LOGFILE=$1

SP=/system/bin/setprop

# for some reason script /vendor/etc/vendor.memplus.sh keeps hanging
# in an endless sleep loop
# terminate it by setting vendor.sys.memplus.postboot to 2

if /system/bin/grep '/vendor/etc/vendor.memplus.sh' `/system/bin/toybox ps -A -o user,pid,ppid,nice,args`; then
    echo "-- process 'sh /vendor/etc/vendor.memplus.sh' is running" | tee -a $LOGFILE
else
    echo "-- process 'sh /vendor/etc/vendor.memplus.sh' is NOT running" | tee -a $LOGFILE
fi

SLEEP=10
echo "-- sleeping $SLEEP seconds before setting vendor.sys.memplus.postboot to 2" | tee -a $LOGFILE

sleep $SLEEP
$SP vendor.sys.memplus.postboot 2
