#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

echo "-- not running script $0 ... seems not needed" | $TEE $LOGFILE
exit 0


waitforsdcard $LOGFILE

sleep 10

echo "-- running update_verifier to signal successful boot" | $TEE $LOGFILE
/system/bin/update_verifier
