#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

waitforsdcard $LOGFILE

echo "-- setting default launcher" | $TEE $LOGFILE
$CMD package set-home-activity com.teslacoilsw.launcher/.NovaLauncher
