#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

waitforsdcard $LOGFILE

echo "-- disabling packages" | $TEE $LOGFILE
$CMD package disable android.autoinstalls.config.oneplus
$CMD package disable cn.oneplus.nvbackup
$CMD package disable cn.oneplus.oemtcma
$CMD package disable cn.oneplus.opmms
$CMD package disable cn.oneplus.photos
$CMD package disable com.android.backup
$CMD package disable com.android.bips
$CMD package disable com.android.bluetoothmidiservice
$CMD package disable com.android.bookmarkprovider
$CMD package disable com.android.carrierdefaultapp
$CMD package disable com.android.companiondevicemanager
$CMD package disable com.android.cts.ctsshim
$CMD package disable com.android.dreams.basic
$CMD package disable com.android.egg
$CMD package disable com.android.htmlviewer
$CMD package disable com.android.pacprocessor
$CMD package disable com.android.providers.partnerbookmarks
$CMD package disable com.android.simappdialog
$CMD package disable com.android.smspush
$CMD package disable com.android.traceur
$CMD package disable com.android.wallpaper.livepicker
$CMD package disable com.android.wallpaperbackup
$CMD package disable com.dsi.ant.server
$CMD package disable com.example.wifirftest
$CMD package disable com.fingerprints.fingerprintsensortest
$CMD package disable com.google.android.printservice.recommendation
$CMD package disable com.oem.autotest
$CMD package disable com.oem.logkitsdservice
$CMD package disable com.oem.nfc
$CMD package disable com.oem.oemlogkit
$CMD package disable com.oem.rftoolkit
$CMD package disable com.oneplus.appupgrader
$CMD package disable com.oneplus.asti
$CMD package disable com.oneplus.backuprestore.remoteservice
$CMD package disable com.oneplus.brickmode
$CMD package disable com.oneplus.bttestmode
$CMD package disable com.oneplus.calculator
$CMD package disable com.oneplus.deskclock
$CMD package disable com.oneplus.diagnosemanager
$CMD package disable com.oneplus.factorymode
$CMD package disable com.oneplus.factorymode.specialtest
$CMD package disable com.oneplus.filemanager
$CMD package disable com.oneplus.gamespace
$CMD package disable com.oneplus.geoiptime
$CMD package disable com.oneplus.opbackup
$CMD package disable com.oneplus.opbugreportlite
$CMD package disable com.oneplus.screenrecord
$CMD package disable com.oneplus.sdcardservice
$CMD package disable com.oneplus.ses
$CMD package disable com.oneplus.sms.smscplugger
$CMD package disable com.oneplus.sound.tuner
$CMD package disable com.oneplus.wallpaper
$CMD package disable com.qualcomm.qti.qcolor
$CMD package disable com.tencent.soter.soterserver
$CMD package disable com.wapi.wapicertmanage
$CMD package disable net.oneplus.commonlogtool
$CMD package disable net.oneplus.push
$CMD package disable net.oneplus.wallpaperresources
