#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

sleep 10

if [ -e /system/xbin/freeze ]; then
    echo "-- freezing apps" | $TEE $LOGFILE
    /system/xbin/freeze disable | sed 's/Package/   -- freezing:/g' | $TEE $LOGFILE
else
    echo "-- /system/xbin/freeze does not exist" | $TEE $LOGFILE
fi

