#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

waitforsdcard $LOGFILE

echo "-- sleeping for an additional 25 seconds to make sure all processes have started" | $TEE $LOGFILE
sleep 25

#if [ `getprop ro.build.version.sdk` -eq 29 ]; then
#    echo "-- we're on android 10, not running this script" | $TEE $LOGFILE
#    exit 0
#fi

changepriority () {
    PROCESS="$1"
    PRIORITY="$2"
    PID=$($BB pgrep $PROCESS | head -n 1)
    if [ "$PRIORITY" -lt "0" ]; then
        CHANGE=increasing
    else
        CHANGE=decreasing
    fi
    CURPRIO=$($TB ps -A -o user,pid,ppid,nice,args | grep $PROCESS | grep -v grep | awk '{print $4}')
    $TB renice -n "$PRIORITY" "$PID"
    NEWPRIO=$($TB ps -A -o user,pid,ppid,nice,args | grep $PROCESS | grep -v grep | awk '{print $4}')
    echo "-- $CHANGE priority ($CURPRIO) of process $PROCESS ($PID) with $PRIORITY (new: $NEWPRIO)" | $TEE $LOGFILE
}

changepriority logd 10
changepriority storaged 3
changepriority dpmQmiMgr 3
changepriority healthd 3
changepriority lmkd 3
changepriority system_server -18
changepriority surfaceflinger -12
changepriority zygote64 -8
changepriority com.android.systemui -15
changepriority com.teslacoilsw.launcher -5
