#!/system/bin/sh

LOGFILE=$1

. /etc/init.d/googlewiz.sh

if [ $(getprop ro.build.version.sdk) -ne 29 ]; then
    echo "-- we're NOT on android 10, not running this script" | tee -a $LOGFILE
    exit 0
fi

waitforsdcard $LOGFILE

BB=/system/xbin/busybox
CMD=/system/bin/cmd

echo "-- changing secure setting dialer_default_application" | tee -a $LOGFILE
$CMD settings put secure dialer_default_application com.google.android.dialer
