#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

MOUNT="$TB mount"

sleep 10

echo "-- installing busybox in /system/bin" | $TEE $LOGFILE
$MOUNT -o rw,remount /
$BB --install -s /system/bin/
$MOUNT -o ro,remount /
