#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

MOUNT="$BB mount -o remount,noatime,nodiratime"

$MOUNT /data
echo "-- $MOUNT /data"
$MOUNT /product
echo "-- $MOUNT /product"
$MOUNT /vendor
echo "-- $MOUNT /vendor"
