#!/system/bin/sh

LOGFILE=$1
BB=/system/xbin/busybox
TB=/system/bin/toybox
MOUNT="$TB mount"

sleep 10

echo "-- installing busybox in /system/bin" | tee -a $LOGFILE
$MOUNT -o rw,remount /
$BB --install -s /system/bin/
$MOUNT -o ro,remount /
