#!/system/bin/sh

# we should only run once !
if [ -f "/data/.googlewiz.touch" ]; then exit 0; fi

LOGFILE=$1
. /etc/init.d/googlewiz.sh

if [ $($GETPROP ro.build.version.sdk) -ne 29 ]; then
    echo "-- we're NOT on android 10, not running this script" | $TEE $LOGFILE
    exit 0
fi

waitforsdcard $LOGFILE

echo "-- changing global settings" | $TEE $LOGFILE
$SETTINGSPUT global activity_starts_logging_enabled 0
$SETTINGSPUT global adaptive_battery_management_enabled 0
$SETTINGSPUT global adb_enabled 1
$SETTINGSPUT global add_users_when_locked 0
$SETTINGSPUT global airplane_mode_on 0
$SETTINGSPUT global airplane_mode_radios cell,bluetooth,wifi,nfc,wimax
$SETTINGSPUT global airplane_mode_toggleable_radios bluetooth,wifi,nfc
$SETTINGSPUT global animator_duration_scale 0.0
$SETTINGSPUT global assisted_gps_enabled 1
$SETTINGSPUT global auto_time 1
$SETTINGSPUT global auto_time_zone 1
$SETTINGSPUT global bluetooth_on 1
$SETTINGSPUT global data_roaming1 1
$SETTINGSPUT global data_roaming2 0
$SETTINGSPUT global data_roaming 0
$SETTINGSPUT global dock_audio_media_enabled 0
$SETTINGSPUT global dock_sounds_enabled 0
$SETTINGSPUT global dock_sounds_enabled_when_accessbility 0
$SETTINGSPUT global development_settings_enabled 1
$SETTINGSPUT global device_name 'OnePlus 7T pro'
$SETTINGSPUT global enable_cache_quota_calculation 0
$SETTINGSPUT global enable_diskstats_logging 0
$SETTINGSPUT global enable_gpu_debug_layers 0
$SETTINGSPUT global enable_gnss_raw_meas_full_tracking 0
$SETTINGSPUT global guest_user_enabled 0
$SETTINGSPUT global heads_up_notifications_enabled 0
$SETTINGSPUT global low_power 0
$SETTINGSPUT global mobile_data0 1
$SETTINGSPUT global mobile_data1 1
$SETTINGSPUT global mobile_data 1
$SETTINGSPUT global mobile_data_always_on 0
$SETTINGSPUT global mobile_data_network_enable 0
$SETTINGSPUT global netstats_enabled 0
$SETTINGSPUT global network_recommendations_enabled 0
$SETTINGSPUT global network_scoring_ui_enabled 0
$SETTINGSPUT global network_watchlist_enabled 0
$SETTINGSPUT global oem_black_mode 1
$SETTINGSPUT global oneplus_otg_auto_disable 1
$SETTINGSPUT global oneplus_permission_agree 1
$SETTINGSPUT global oneplus_screen_refresh_rate 0
$SETTINGSPUT global oneplus_screen_resolution_adjust 0
$SETTINGSPUT global op_video_enhancer 1
$SETTINGSPUT global ota_disable_automatic_update 1
$SETTINGSPUT global package_verifier_enable 1
$SETTINGSPUT global power_sounds_enabled 1
$SETTINGSPUT global persist_wifi_country_code BE
$SETTINGSPUT global require_password_to_decrypt 0
$SETTINGSPUT global sysui_demo_allowed 0
$SETTINGSPUT global stay_on_while_plugged_in 0
$SETTINGSPUT global transition_animation_scale 0.0
$SETTINGSPUT global upload_apk_enable 0
$SETTINGSPUT global usb_mass_storage_enabled 0
$SETTINGSPUT global wait_for_debugger 0
$SETTINGSPUT global wifi_auto_change_to_mobile_data 0
$SETTINGSPUT global wifi_display_on 0
$SETTINGSPUT global wifi_ipv6_supported 1
$SETTINGSPUT global wifi_networks_available_notification_on 0
$SETTINGSPUT global wifi_scan_always_enabled 0
$SETTINGSPUT global wifi_verbose_logging_enabled 0
$SETTINGSPUT global window_animation_scale 0.0
$SETTINGSPUT global zram_enabled 0

echo "-- changing system settings" | $TEE $LOGFILE
$SETTINGSPUT system aod_smart_display_enabled 1
$SETTINGSPUT system aod_smart_display_cur_state 0
$SETTINGSPUT system auto_switch_mobile_data 1
$SETTINGSPUT system battery_led_charging 0
$SETTINGSPUT system buttons_show_on_screen_navkeys 0
$SETTINGSPUT secure clock_seconds 0
$SETTINGSPUT system date_format dd-mm-yyyy
$SETTINGSPUT system dim_screen 1
$SETTINGSPUT system direct_share 0
$SETTINGSPUT system display_battery_percentage 1
$SETTINGSPUT system dtmf_tone 1
$SETTINGSPUT system esport_mode_enabled 0
$SETTINGSPUT system font_scale 1.0
$SETTINGSPUT system game_mode_status 0
$SETTINGSPUT system haptic_feedback_enabled 1
$SETTINGSPUT system hearing_aid 0
$SETTINGSPUT system incoming_call_vibrate_intensity 3
$SETTINGSPUT system incoming_call_vibrate_mode 5
$SETTINGSPUT system launcher_iconpack none
$SETTINGSPUT system lockscreen_sounds_enabled 1
$SETTINGSPUT system notice_vibrate_intensity 2
$SETTINGSPUT system notification_light_pulse 0
$SETTINGSPUT system oem_acc_control_music 0
$SETTINGSPUT system oem_acc_control_next 0
$SETTINGSPUT system oem_acc_control_pause 0
$SETTINGSPUT system oem_acc_control_play 0
$SETTINGSPUT system oem_acc_control_prev 0
$SETTINGSPUT system oem_acc_night_mode 0
$SETTINGSPUT system oem_acc_open_flashlight 0
$SETTINGSPUT system oem_acc_startup_camera 0
$SETTINGSPUT system oem_agree_incall_people 0
$SETTINGSPUT system oem_allow_led_light 0
$SETTINGSPUT system oem_allow_suspend_notification 1
$SETTINGSPUT system oem_app_updates_enable 0
$SETTINGSPUT system oem_auto_play 0
$SETTINGSPUT system oem_black_mode 1
$SETTINGSPUT system oem_black_mode_accent_color '#FFbe0029'
$SETTINGSPUT system oem_eyecare_enable 0
$SETTINGSPUT system oem_finger_check_oneplus_account 0
$SETTINGSPUT system oem_font_mode 1
$SETTINGSPUT system oem_join_stability_plan_settings 0
$SETTINGSPUT system oem_join_user_plan_settings 0
$SETTINGSPUT system oem_oneplus_devicename 'OnePlus 7T pro'
$SETTINGSPUT system oem_quick_clipboard 1
$SETTINGSPUT system oem_screenshot_sound_enable 1
$SETTINGSPUT system oem_service_messaging_enable 0
$SETTINGSPUT system oem_share_wifi 0
$SETTINGSPUT system oem_vibrate_under_silent 0
$SETTINGSPUT system oem_zen_media_switch 1
$SETTINGSPUT system oem_zen_mode_enable 0
$SETTINGSPUT system oem_zen_status 0
$SETTINGSPUT system oneplus_accent_color '#ffbe0029'
$SETTINGSPUT system oneplus_card_disabled 1
$SETTINGSPUT system oneplus_auto_face_unlock_enable 0
$SETTINGSPUT system oneplus_fullscreen_gesture_type 1
$SETTINGSPUT system op_custom_horizon_light_animation_style 3
$SETTINGSPUT system op_custom_unlock_animation_style 9
$SETTINGSPUT system op_customization_theme_style 1
$SETTINGSPUT system op_default_app_camera com.oneplus.camera
$SETTINGSPUT system op_default_app_email com.google.android.gm
$SETTINGSPUT system op_default_app_gallery com.google.android.apps.photos
$SETTINGSPUT system op_default_app_music com.maxmpz.audioplayer
$SETTINGSPUT system op_default_country_code 'Belgium;+32'
$SETTINGSPUT system op_smartboost_enable 0
$SETTINGSPUT system optimal_power_save_mode_enabled 0
$SETTINGSPUT system reading_mode_status 0
$SETTINGSPUT system require_password_to_decrypt 0
$SETTINGSPUT system screen_auto_brightness_adj 0.0
$SETTINGSPUT system screen_brightness_mode 1
$SETTINGSPUT system screen_color_mode_advanced_settings_value 1
$SETTINGSPUT system screen_color_mode_settings_value 3
$SETTINGSPUT system screen_off_timeout 300000
$SETTINGSPUT system sound_effects_enabled 0
$SETTINGSPUT system status_bar_battery_style 2
$SETTINGSPUT system status_bar_keyquard_visibility 0
$SETTINGSPUT system status_bar_show_battery_percent 1
$SETTINGSPUT system system_locales nl-BE,en-BE
$SETTINGSPUT system systemui_navigation_bar_hided 0

echo "-- changing secure settings" | $TEE $LOGFILE
$SETTINGSPUT secure accessibility_enabled 0
$SETTINGSPUT secure accessibility_shortcut_enabled 0
$SETTINGSPUT secure advanced_reboot 1
$SETTINGSPUT secure aod_clock_style 0
$SETTINGSPUT secure aod_display_text 'Philip Rademakers'
$SETTINGSPUT secure aware_enabled not_set
$SETTINGSPUT secure aware_lock_enabled 0
$SETTINGSPUT secure automatic_storage_manager_enabled 0
$SETTINGSPUT secure backup_enabled:com.android.calllogbackup 0
$SETTINGSPUT secure backup_enabled:com.android.providers.telephony 0
$SETTINGSPUT secure backup_enabled 0
$SETTINGSPUT secure backup_encryption_opt_in_displayed 0
$SETTINGSPUT secure bluetooth_aptx_hd 1
$SETTINGSPUT secure bluetooth_name 'OnePlus 7T pro'
$SETTINGSPUT secure brightness_auto 1
$SETTINGSPUT secure brightness_on_top 1
$SETTINGSPUT secure charging_sounds_enabled 1
$SETTINGSPUT secure charging_vibration_enabled 1
$SETTINGSPUT secure clock_seconds 0
$SETTINGSPUT secure development_settings_enabled 1
$SETTINGSPUT secure dialer_default_application com.google.android.dialer
$SETTINGSPUT secure double_tap_to_wake 1
$SETTINGSPUT secure doze_enabled 1
$SETTINGSPUT secure flashlight_available 1
$SETTINGSPUT secure flashlight_enabled 0
$SETTINGSPUT secure install_non_market_apps 1
$SETTINGSPUT secure instant_apps_enabled 0
$SETTINGSPUT secure location_providers_allowed gps,network
$SETTINGSPUT secure lock_screen_allow_private_notifications 0
$SETTINGSPUT secure lock_screen_owner_info_enabled 1
$SETTINGSPUT secure lock_screen_show_notifications 0
$SETTINGSPUT secure lock_screen_show_silent_notifications 0
$SETTINGSPUT secure lockdown_in_power_menu 1
$SETTINGSPUT secure lockscreen.disabled 0
$SETTINGSPUT secure lockscreen.options enable_facelock
$SETTINGSPUT secure night_display_activated 0
$SETTINGSPUT secure navigation_mode 2
$SETTINGSPUT secure notification_badging 1
$SETTINGSPUT secure notification_bubbles 0
$SETTINGSPUT secure notification_wake_enabled 0
$SETTINGSPUT secure qs_auto_tiles inversion
$SETTINGSPUT secure qs_tile_column 7
$SETTINGSPUT secure qs_tile_text_size 48
$SETTINGSPUT secure screensaver_activate_on_dock 0
$SETTINGSPUT secure screensaver_activate_on_sleep 0
$SETTINGSPUT secure screensaver_enabled 0
$SETTINGSPUT secure show_zen_settings_suggestion 0
$SETTINGSPUT secure sysui_force_enable_leak_reporting 0
$SETTINGSPUT secure sysui_qqs_count 7
$SETTINGSPUT secure sysui_qs_tiles 'wifi,bt,cell,location,nfc,flashlight,airplane,night,hotspot,custom(projekt.substratum/.services.tiles.SubstratumTile),cast,inversion,custom(com.google.android.apps.nbu.files/.quicksettings.StorageAssistantTileService),custom(com.teacapps.barcodescanner.pro/net.qrbot.quicksettings.ScanTileService),custom(ch.protonvpn.android/com.protonvpn.android.components.QuickTileService)'
$SETTINGSPUT secure touch_exploration_enabled 0
$SETTINGSPUT secure ui_night_mode 2
$SETTINGSPUT secure user_full_data_backup_aware 1
$SETTINGSPUT secure wake_gesture_enabled 1
$SETTINGSPUT secure wifi_idle_ms 300000
$SETTINGSPUT secure wifi_suspend_optimizations_enabled 1
$SETTINGSPUT secure wifi_watchdog_poor_network_test_enabled 0

echo "-- granting permissions for com.google.android.contacts" | $TEE $LOGFILE
$CMD package grant com.google.android.contacts android.permission.READ_CALENDAR 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.READ_CALL_LOG 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.ACCESS_FINE_LOCATION 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.READ_EXTERNAL_STORAGE 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.ACCESS_COARSE_LOCATION 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.READ_PHONE_STATE 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.SEND_SMS 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.CALL_PHONE 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.WRITE_CONTACTS 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.CAMERA 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.WRITE_CALL_LOG 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.PROCESS_OUTGOING_CALLS 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.GET_ACCOUNTS 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.WRITE_EXTERNAL_STORAGE 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.RECORD_AUDIO 2> /dev/null
$CMD package grant com.google.android.contacts android.permission.READ_CONTACTS 2> /dev/null

echo "-- granting permissions for com.google.android.dialer" | $TEE $LOGFILE
$CMD package grant com.google.android.dialer android.permission.READ_CALENDAR 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.READ_CALL_LOG 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.ACCESS_FINE_LOCATION 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.READ_EXTERNAL_STORAGE 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.ACCESS_COARSE_LOCATION 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.READ_PHONE_STATE 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.SEND_SMS 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.CALL_PHONE 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.WRITE_CONTACTS 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.CAMERA 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.WRITE_CALL_LOG 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.PROCESS_OUTGOING_CALLS 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.GET_ACCOUNTS 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.WRITE_EXTERNAL_STORAGE 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.RECORD_AUDIO 2> /dev/null
$CMD package grant com.google.android.dialer android.permission.READ_CONTACTS 2> /dev/null
$CMD package grant com.google.android.dialer com.android.voicemail.permission.ADD_VOICEMAIL 2> /dev/null

echo "-- granting permissions for com.google.android.apps.wellbeing" | $TEE $LOGFILE
$CMD package grant com.google.android.apps.wellbeing android.permission.WRITE_EXTERNAL_STORAGE

$CMD appops set com.google.android.dialer SYSTEM_ALERT_WINDOW allow

# turn off NFC
echo "-- turn off NFC" | $TEE $LOGFILE
/system/bin/service call nfc 6 > /dev/null

# this file seems to be missing (logcat)
touch /data/system/smartcontrol.xml

# now make sure this script so it runs exactly once
echo "-- touch /data/.googlewiz.touch" | $TEE $LOGFILE
$BB touch /data/.googlewiz.touch
