#!/system/bin/sh

MODULE=/sbin/.magisk/modules/googlewiz

TARF=/sdcard/modappsq.tar
rm -rf $TARF
cd $MODULE
echo "Creating $TARF"
tar cfp $TARF \
    vendor/app/My*
NUM=$(tar tvf $TARF  | grep '\.apk' | grep base | wc -l)
echo "$NUM APKs included in $TARF"
sync
sync
