#!/system/bin/sh

LOGFILE=$1

# protect against incorrect /proc mounts
# thanks to Topjohnwu
# https://forums.oneplus.com/threads/fix-released-serious-security-bleach-found-in-oxygenos.949461/

echo "-- remounting: mount -o remount,hidepid=2,gid=3009 /proc" | tee -a $LOGFILE
/system/bin/toybox mount -o remount,hidepid=2,gid=3009 /proc
