#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

echo "-- applying scheduling tweaks" | $TEE $LOGFILE
sysset 7000000 /proc/sys/kernel/sched_latency_ns
sysset 60 /proc/sys/kernel/sched_rr_timeslice_ms
