#!/system/bin/sh

LOGFILE=$1

. /etc/init.d/googlewiz.sh

sleep 25

echo "-- trying to schange CPU governors" | tee -a $LOGFILE

for CPU in 0 1 2 3 4 5 6 7; do
    chmod 644 /sys/devices/system/cpu/cpu$CPU/cpufreq/scaling_governor
done

SGOV=false
GOV=schedutil_pixel
for CPU in 0 4 7; do
    CURRENT=`cat /sys/devices/system/cpu/cpufreq/policy$CPU/scaling_governor`
    if grep $GOV /sys/devices/system/cpu/cpufreq/policy$CPU/scaling_available_governors; then
        SGOV=true
        sysset $GOV /sys/devices/system/cpu/cpu$CPU/cpufreq/scaling_governor
        sysset 1 /sys/devices/system/cpu/cpu$CPU/cpufreq/$GOV/pl
        sysset 5000 /sys/devices/system/cpu/cpu$CPU/cpufreq/$GOV/down_rate_limit_us
        sysset 0 /sys/devices/system/cpu/cpu$CPU/cpufreq/$GOV/up_rate_limit_us
    else
        echo "-- governor: $GOV does not exist for CPU: $CPU (keeping: $CURRENT)" | tee -a $LOGFILE
    fi
done

if [ "$SGOV" = "false" ]; then
    GOV=schedutil
    for CPU in 0 4 7; do
        if grep $GOV /sys/devices/system/cpu/cpufreq/policy$CPU/scaling_available_governors; then
            sysset $GOV /sys/devices/system/cpu/cpu$CPU/cpufreq/scaling_governor
            MAXFREQ=`cat /sys/devices/system/cpu/cpufreq/policy$CPU/scaling_max_freq`
            sysset $MAXFREQ /sys/devices/system/cpu/cpufreq/policy$CPU/$GOV/hispeed_freq
        else
            echo "-- governor: $GOV does not exist for CPU: $CPU (keeping: $CURRENT)" | tee -a $LOGFILE
        fi
    done
else
    echo "-- weird: this should not happen ..." | tee -a $LOGFILE
fi
