#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

N=60
sleep "$N" 

echo "-- slept for $N seconds" | $TEE $LOGFILE
echo "-- applying touchboost tweaks" | $TEE $LOGFILE
MAXFREQ0=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies | sed 's/ /\n/g' | sed '/^ *$/d' | sort -n -r | head -n 1)
MAXFREQ4=$(cat /sys/devices/system/cpu/cpu4/cpufreq/scaling_available_frequencies | sed 's/ /\n/g' | sed '/^ *$/d' | sort -n -r | head -n 1)
MAXFREQ7=$(cat /sys/devices/system/cpu/cpu7/cpufreq/scaling_available_frequencies | sed 's/ /\n/g' | sed '/^ *$/d' | sort -n -r | head -n 1)

sysset "0:$MAXFREQ0 1:0 2:0 3:0 4:$MAXFREQ4 5:0 6:0 7:$MAXFREQ7" /sys/module/cpu_boost/parameters/input_boost_freq
# give it 3 seconds at max frequenties
sysset 3000 /sys/module/cpu_boost/parameters/input_boost_ms
