#!/system/bin/sh

LOGFILE=$1
. /etc/init.d/googlewiz.sh

# protect against incorrect /proc mounts
# thanks to Topjohnwu
# https://forums.oneplus.com/threads/fix-released-serious-security-bleach-found-in-oxygenos.949461/

echo "-- remounting: mount -o remount,hidepid=2,gid=3009 /proc" | $TEE $LOGFILE
$TB mount -o remount,hidepid=2,gid=3009 /proc
