#!/system/bin/sh

LOGFILE=$1

. /etc/init.d/googlewiz.sh

echo "-- disabling debugging" | tee -a $LOGFILE
set_debug 0 debug
set_debug 0 debug_level
set_debug 0 debug_mask
set_debug 0 edac_mc_log_ce
set_debug 0 edac_mc_log_ue
set_debug 0 enable_debug
set_debug 0 enable_event_log
set_debug 1 log_disable
set_debug 0 log_ecn_error
set_debug 0 log_lv
set_debug 0 scsi_logging_level
set_debug 0 snapshot_crashdumper

echo "-- changing kernel sysctl" | tee -a $LOGFILE
sysset 0 /proc/sys/debug/exception-trace
sysset 0 /proc/sys/kernel/ctrl-alt-del
sysset 0 /proc/sys/kernel/dmesg_restrict
sysset 0 /proc/sys/kernel/panic
sysset 0 /proc/sys/kernel/panic_on_oops
sysset 0 /proc/sys/kernel/panic_on_warn
sysset 0 /proc/sys/kernel/perf_cpu_time_max_percent
sysset "0 0 0 0" /proc/sys/kernel/printk
sysset 0 /proc/sys/kernel/printk_delay
sysset 0 /proc/sys/kernel/printk_ratelimit
sysset off /proc/sys/kernel/printk_devkmsg
sysset 0 /proc/sys/kernel/randomize_va_space
sysset 0 /proc/sys/kernel/sched_schedstats
sysset 0 /sys/kernel/debug/debug_enabled

echo "-- changing vm sysctls" | tee -a $LOGFILE

sysset 0 /proc/sys/vm/block_dump
sysset 1 /proc/sys/vm/compact_memory
sysset 1 /proc/sys/vm/compact_unevictable_allowed
sysset 15 /proc/sys/vm/dirty_background_ratio
sysset 300 /proc/sys/vm/dirty_expire_centisecs
sysset 20 /proc/sys/vm/dirty_ratio
sysset 400 /proc/sys/vm/dirty_writeback_centisecs
sysset 3 /proc/sys/vm/drop_caches
sysset 0 /proc/sys/vm/laptop_mode
sysset 8196 /proc/sys/vm/min_free_kbytes
sysset 0 /proc/sys/vm/oom_dump_tasks
sysset 0 /proc/sys/vm/oom_kill_allocating_task
sysset 1 /proc/sys/vm/overcommit_memory
sysset 0 /proc/sys/vm/overcommit_ratio
sysset 0 /proc/sys/vm/page-cluster
sysset 0 /proc/sys/vm/panic_on_oom
sysset 0 /proc/sys/vm/stat_interval
sysset 0 /proc/sys/vm/swappiness
sysset 0 /proc/sys/vm/vfs_cache_pressure

echo "-- changing module sysctl" | tee -a $LOGFILE
sysset N /sys/module/kernel/parameters/initcall_debug
sysset Y /sys/module/printk/parameters/console_suspend
sysset 0 /sys/module/subsystem_restart/parameters/enable_mini_ramdumps
sysset 0 /sys/module/subsystem_restart/parameters/enable_ramdumps

echo "-- disable misc debug in kernel" | tee -a $LOGFILE
sysset N /sys/kernel/debug/debug_enabled
sysset 0 /sys/kernel/debug/1d84000.ufshc/qcom/testbus/enable
sysset 0 /sys/kernel/debug/msm_vidc/fw_debug_mode
sysset 0 /sys/kernel/debug/msm_vidc/debug_level
sysset 0 /sys/kernel/debug/dri/0/debug/hw_log_mask
sysset N /sys/kernel/debug/sched_debug
sysset 0 /sys/kernel/debug/sde_rotator0/evtlog/enable
sysset N /sys/kernel/debug/drm_dp/fec_feature_enable
sysset N /sys/kernel/debug/drm_dp/dsc_feature_enable

echo "-- applying scheduling tweaks" | tee -a $LOGFILE
for i in /proc/sys/kernel; do
    echo 84 84 > $i/sched_downmigrate
    echo 95 > $i/sched_group_downmigrate
    echo 100 > $i/sched_group_upmigrate
    echo 94 94 > $i/sched_upmigrate
    echo 0 > $i/sched_walt_rotate_big_tasks
done

echo "-- miscellaneous kernel settings" | tee -a $LOGFILE
sysset Y /sys/module/bluetooth/parameters/disable_ertm
sysset Y /sys/module/bluetooth/parameters/disable_esco
sysset Y /sys/module/cryptomgr/parameters/notests
sysset 0 /sys/module/diagchar/parameters/diag_mask_clear_param
sysset 0 /sys/module/dwc3/parameters/ep_addr_rxdbg_mask
sysset 0 /sys/module/dwc3/parameters/ep_addr_txdbg_mask
sysset 1 /sys/module/hid/parameters/ignore_special_drivers
sysset 0 /sys/module/hid_apple/parameters/fnmode
sysset 0 /sys/module/hid_apple/parameters/iso_layout
sysset N /sys/module/hid_magicmouse/parameters/emulate_3button
sysset N /sys/module/hid_magicmouse/parameters/emulate_scroll_wheel
sysset 0 /sys/module/icnss/parameters/dynamic_feature_mask
sysset N /sys/module/ppp_generic/parameters/mp_protocol_compress
sysset 0 /sys/module/service_locator/parameters/enable
sysset 25000 /sys/power/pm_freeze_timeout

echo "-- disable kernel sleepers" | tee -a $LOGFILE
sysset NO_GENTLE_FAIR_SLEEPERS /sys/kernel/debug/sched_features

echo "-- disable all tracing" | tee -a $LOGFILE
sysset 0 /sys/kernel/debug/tracing/events/jbd2/jbd2_commit_logging/enable
sysset 0 /sys/kernel/debug/tracing/events/sde/sde_evtlog/enable
sysset 0 /sys/kernel/debug/tracing/instances/wifi/tracing_on
sysset 0 /sys/kernel/debug/tracing/instances/wifi/tracing_on
sysset 0 /sys/kernel/debug/tracing/tracing_on
sysset 0 /sys/module/qpnp_power_on/parameters/long_pwr_dump_enabled
sysset 0 /sys/module/qpnp_power_on/parameters/pwr_dump_enabled
sysset 0 /sys/module/ramoops/parameters/dump_oops

echo "-- changing file system sysctls" | tee -a $LOGFILE
sysset 0 /proc/sys/fs/dir-notify-enable
sysset 262144 /proc/sys/fs/file-max
sysset 20 /proc/sys/fs/lease-break-time
sysset 1 /proc/sys/fs/leases-enable

echo "-- changing net.core sysctls" | tee -a $LOGFILE
sysset 8738000 /proc/sys/net/core/rmem_max
sysset 6553600 /proc/sys/net/core/wmem_max
sysset 0 /proc/sys/net/core/netdev_tstamp_prequeue

echo "-- changing ipv4 sysctls" | tee -a $LOGFILE
sysset 0 /proc/sys/net/ipv4/cipso_cache_bucket_size
sysset 0 /proc/sys/net/ipv4/cipso_cache_enable
sysset 0 /proc/sys/net/ipv4/cipso_rbm_strictvalid
sysset 0 /proc/sys/net/ipv4/conf/all/accept_redirects
sysset 0 /proc/sys/net/ipv4/conf/all/accept_source_route
sysset 2 /proc/sys/net/ipv4/conf/all/rp_filter
sysset 0 /proc/sys/net/ipv4/conf/all/secure_redirects
sysset 0 /proc/sys/net/ipv4/conf/default/accept_redirects
sysset 0 /proc/sys/net/ipv4/conf/default/accept_source_route
sysset 2 /proc/sys/net/ipv4/conf/default/rp_filter
sysset 0 /proc/sys/net/ipv4/conf/default/secure_redirects
sysset 1 /proc/sys/net/ipv4/icmp_echo_ignore_all
sysset 1 /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
sysset 0 /proc/sys/net/ipv4/igmp_link_local_mcast_reports
sysset 0 /proc/sys/net/ipv4/ip_forward
sysset 24 /proc/sys/net/ipv4/ipfrag_time
sysset 0 /proc/sys/net/ipv4/ip_no_pmtu_disc
sysset 1 /proc/sys/net/ipv4/route/flush
sysset westwood /proc/sys/net/ipv4/tcp_congestion_control
sysset 1 /proc/sys/net/ipv4/tcp_dsack
sysset 0 /proc/sys/net/ipv4/tcp_ecn
sysset 1 /proc/sys/net/ipv4/tcp_fack
sysset 45 /proc/sys/net/ipv4/tcp_fin_timeout
sysset 0 /proc/sys/net/ipv4/tcp_fwmark_accept
sysset 45 /proc/sys/net/ipv4/tcp_keepalive_intvl
sysset 4 /proc/sys/net/ipv4/tcp_keepalive_probes
sysset 3600 /proc/sys/net/ipv4/tcp_keepalive_time
sysset 1 /proc/sys/net/ipv4/tcp_low_latency
sysset 65536 /proc/sys/net/ipv4/tcp_max_orphans
sysset 16384 /proc/sys/net/ipv4/tcp_max_syn_backlog
sysset 65536 /proc/sys/net/ipv4/tcp_max_tw_buckets
sysset 1 /proc/sys/net/ipv4/tcp_moderate_rcvbuf
sysset 1 /proc/sys/net/ipv4/tcp_no_metrics_save
sysset 1800 /proc/sys/net/ipv4/tcp_probe_interval
sysset 8 /proc/sys/net/ipv4/tcp_retries2
sysset 1 /proc/sys/net/ipv4/tcp_rfc1337
sysset 1 /proc/sys/net/ipv4/tcp_sack
sysset 0 /proc/sys/net/ipv4/tcp_slow_start_after_idle
sysset 2 /proc/sys/net/ipv4/tcp_synack_retries
sysset 0 /proc/sys/net/ipv4/tcp_syncookies
sysset 6 /proc/sys/net/ipv4/tcp_syn_retries
sysset 0 /proc/sys/net/ipv4/tcp_timestamps
sysset 2 /proc/sys/net/ipv4/tcp_tw_reuse
sysset 1 /proc/sys/net/ipv4/tcp_window_scaling
sysset 6144 /proc/sys/net/ipv4/udp_rmem_min
sysset 6144 /proc/sys/net/ipv4/udp_wmem_min

echo "-- changing ipv6 sysctls" | tee -a $LOGFILE
sysset 0 /proc/sys/net/ipv6/calipso_cache_bucket_size
sysset 0 /proc/sys/net/ipv6/calipso_cache_enable
sysset 36 /proc/sys/net/ipv6/ip6frag_time
sysset 1 /proc/sys/net/ipv6/route/flush

echo "-- changing netfilter sysctls" | tee -a $LOGFILE
sysset 1048576 /proc/sys/net/netfilter/nf_conntrack_max
sysset 2 /proc/sys/net/netfilter/nf_conntrack_tcp_max_retrans
