#!/system/bin/sh

LOGFILE=$1
RM=/system/bin/rm
FIND=/system/xbin/find
XARGS=toybox xargs

echo "-- deleting cache files in /data/data" | tee -a $LOGFILE
for dir in $($FIND /data/data -type d -iname '*cache*'); do
    $FIND "$dir" -type f -delete
done

echo "-- deleting *.tmp files in /data and /cache" | tee -a $LOGFILE
$FIND /data -type f -not -path "/data/media/*" -prune -name '*.tmp' -delete
$FIND /cache -type f -name '*.tmp' -delete

echo "-- deleting all files in /data/system/dropbox" | tee -a $LOGFILE
$RM -rf /data/system/dropbox/*

echo "-- deleting all files in /data/system/usagestats" | tee -a $LOGFILE
$RM -rf /data/system/usagestats/*

echo "-- deleting *.log files in /data" | tee -a $LOGFILE
$FIND /data -type f -not -path "/data/media/*" -prune -name '*.log' -delete

echo "-- deleting misc files from /data" | tee -a $LOGFILE
$RM -rf /cache/*.apk 
$RM -rf /cache/*.tmp 
$RM -rf /cache/*.log 
$RM -rf /cache/*.txt 
$RM -rf /cache/recovery/* 
$RM -rf /data/*.log 
$RM -rf /data/*.txt 
$RM -rf /data/anr/*.log 
$RM -rf /data/anr/*.txt 
$RM -rf /data/backup/pending/*.tmp 
$RM -rf /data/cache/*.* 
$RM -rf /data/dalvik-cache/*.apk 
$RM -rf /data/dalvik-cache/*.tmp 
$RM -rf /data/dalvik-cache/*.log 
$RM -rf /data/dalvik-cache/*.txt 
$RM -rf /data/data/*.log 
$RM -rf /data/data/*.txt 
$RM -rf /data/log/*.log 
$RM -rf /data/log/*.txt 
$RM -rf /data/local/*.apk 
$RM -rf /data/local/*.log 
$RM -rf /data/local/*.txt 
$RM -rf /data/local/tmp/*.log 
$RM -rf /data/local/tmp/*.txt 
$RM -rf /data/last_log/*.log 
$RM -rf /data/last_log/*.txt 
$RM -rf /data/last_alog/*.log 
$RM -rf /data/last_alog/*.txt 
$RM -rf /data/last_kmsg/*.log 
$RM -rf /data/last_kmsg/*.txt 
$RM -rf /data/mlog/* 
$RM -rf /data/tombstones/*.log 
$RM -rf /data/tombstones/*.txt 
$RM -rf /data/system/*.log 
$RM -rf /data/system/*.txt 
$RM -rf /data/system/dropbox/*.log 
$RM -rf /data/system/dropbox/*.txt 
$RM -rf /data/system/usagestats/*.log 
$RM -rf /data/system/usagestats/*.txt 

echo "-- deleting empty directories from /data" | tee -a $LOGFILE
$FIND /data -type d -empty | xargs rm -rf
